name: Delete Image on Branch Deletion

on:
  delete:
    branches: [ '*' ]

env:
  DOCKER_REPOSITORY: ghcr.io

jobs:
  delete-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: github.event.ref_type == 'branch'  # Vérifie que le type de référence supprimée est bien une branche
    steps:
      - name: Display info
        run: echo "Branch ${{ github.event.ref }} has been deleted."
    
      - name: Delete Docker Image from GHCR
        run: |
          IMAGE_TAG=$(echo ${{ github.event.ref }} | tr '/' '-')
          echo "Deleting image ${{ github.repository }} with tag $IMAGE_TAG from ghcr.io..."
          
          # Récupère l'ID du package de l'image
          PACKAGE_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/orgs/YOUR_ORG/packages/container/${{ github.repository }}/versions" | jq -r ".[] | select(.metadata.container.tags[] == \"$IMAGE_TAG\") | .id")
          
          if [ -z "$PACKAGE_ID" ]; then
            echo "No image found for tag $IMAGE_TAG."
          else
            # Supprime l'image avec l'ID du package
            curl -s -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/orgs/YOUR_ORG/packages/container/${{ github.repository }}/versions/$PACKAGE_ID"
            echo "Image with tag $IMAGE_TAG has been deleted."
          fi

