name: Delete Image on Branch Deletion

on:
  delete:
    branches: [ '*' ]

env:
  DOCKER_REPOSITORY: ghcr.io

jobs:
  delete-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: startsWith(github.event.ref_type, 'branch')  # Vérifie que le type de référence supprimée est bien une branche
    steps:
      - name: Display info
        run: echo "Branch ${{ github.event.ref }} has been deleted."
     
      - name: Login to registry ${{ env.DOCKER_REPOSITORY }}
        uses: docker/login-action@v3  # https://github.com/docker/login-action
        with:
            registry: ${{ env.DOCKER_REPOSITORY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Delete Docker Image
        run: |
          IMAGE_ID=${{ env.DOCKER_REPOSITORY }}/${{ github.repository }}:${{ github.event.ref }}
          echo "Check image exists : ${IMAGE_ID}"
          trap 'echo "image doesnt exists" >> "$GITHUB_OUTPUT"' EXIT
          docker manifest inspect ${IMAGE_ID} >/dev/null 2>&1
          trap '' EXIT
          echo "Deleting image : ${IMAGE_ID}"
          docker rmi ${IMAGE_ID}

