name: Delete Image on Branch Deletion

on:
  delete

env:
  DOCKER_REPOSITORY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  delete-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check if ref is a branch
        if: startsWith(github.event.ref, 'refs/heads/')
        run: echo "Branch ${GITHUB_REF} has been deleted."
      - name: Debug
        run: env
     
      - name: Login to registry ${{ env.DOCKER_REPOSITORY }}
        uses: docker/login-action@v3  # https://github.com/docker/login-action
        with:
            registry: ${{ env.DOCKER_REPOSITORY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Delete Docker Image
        run: |
          IMAGE_ID=${IMAGE_NAME}:$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-')
          echo "Check image exists : ${IMAGE_ID}"
          docker manifest inspect ${IMAGE_ID} >/dev/null 2>&1 || return 0
          echo "Deleting image : ${IMAGE_ID}"
          docker rmi ${IMAGE_ID}
